spring:
  datasource:
    hikari:
      username: root
      password: 123456
      # com.mysql.cj.jdbc.Driver => 如果是6.x或者更高版本
      # com.mysql.jdbc.Driver => 如果connect版本是5.x
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.239.37:3306/content_center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
#        namespace: 0674b132-f85c-451f-b5b5-ed81b759294e
        metadata:
          version: v1
          target-version: v1
    sentinel:
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow
        degrade:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
        system:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
        authority:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
        param-flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
      filter:
        # 关闭掉sentinel对于Spring MVC 端点的保护
        enabled: false
      transport:
        # 指定sentinel控制台的地址，因为sentinel是懒加载，需要访问一次api才可以在控制台看到内容
        dashboard: localhost:8080
  application:
    name: content-center

server:
  port: 8010

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# ribbon 配置饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    link.hooray.alibaba.contentcenter.feignclient.UserCenterFeignClient: debug

#feign:
#  client:
#    config:
#      # 想要调用的微服务的名称，实现局部配置
#      user-center:
#        loggerLevel: full

feign:
  # feign整合Sentinel
  sentinel:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    # 让feign 使用apache httpclient做请求，而不是默认urlConnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign 单个路径的最大连接数
    max-connections-per-route: 50
  # 使用 okhttp 作为 客户端
#  okhttp:
#    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'

# 用于调试来用
resttemplate:
  sentinel:
    # 关闭@RestTemplateSentinel 注解
    enabled: false